-- Run with Supabase CLI: supabase db push. Realtime is enabled for every content table.
create type public.translation as (en text,ru text,uz text);
create table public.profile (id uuid primary key default auth.uid(), name public.translation, title public.translation, bio public.translation, photo_url text, cv_url text, location text, languages text[], availability text, contacts jsonb default '{}'::jsonb, counters jsonb default '{}'::jsonb, updated_at timestamptz default now());
create table public.site_settings (id bigint primary key generated always as identity, accent_color text default '#7267f0', default_language text default 'en', default_theme text default 'system', sections jsonb default '{}'::jsonb, seo_title text, seo_description text, favicon_url text, analytics_id text, iframe_allowlist text[] default '{}');
create table public.projects (id uuid primary key default gen_random_uuid(), title jsonb not null default '{"en":""}', summary jsonb not null default '{"en":""}', problem jsonb default '{}', approach jsonb default '{}', tools text[] default '{}', domain text, featured boolean default false, published boolean default false, "order" integer default 0, impact numeric default 0, metrics jsonb default '[]', gallery text[] default '{}', embed_url text, github_url text, demo_url text, file_url text, chart_data jsonb, created_at timestamptz default now());
create table public.skills (id uuid primary key default gen_random_uuid(), name jsonb not null default '{"en":""}', category text, icon text, proficiency integer check(proficiency between 0 and 100), published boolean default false, "order" integer default 0);
create table public.experience (id uuid primary key default gen_random_uuid(), company text, role jsonb default '{}', achievements jsonb default '[]', start_date date, end_date date, published boolean default false, "order" integer default 0);
create table public.certificates (id uuid primary key default gen_random_uuid(), name jsonb default '{}', issuer text, issued_date date, credential_id text, verify_url text, image_url text, published boolean default false, "order" integer default 0);
create table public.education (id uuid primary key default gen_random_uuid(), institution text, degree jsonb default '{}', start_date date, end_date date, published boolean default false, "order" integer default 0);
create table public.testimonials (id uuid primary key default gen_random_uuid(), quote jsonb default '{}', author text, role text, avatar_url text, published boolean default false, "order" integer default 0);
create table public.blog (id uuid primary key default gen_random_uuid(), title jsonb default '{}', body jsonb default '{}', slug text unique, cover_url text, published boolean default false, "order" integer default 0);
create table public.messages (id uuid primary key default gen_random_uuid(), name text not null, email text not null, message text not null, read boolean default false, created_at timestamptz default now());
alter table public.profile enable row level security; alter table public.site_settings enable row level security; alter table public.projects enable row level security; alter table public.skills enable row level security; alter table public.experience enable row level security; alter table public.certificates enable row level security; alter table public.education enable row level security; alter table public.testimonials enable row level security; alter table public.blog enable row level security; alter table public.messages enable row level security;
create policy "public reads published projects" on public.projects for select using (published); create policy "public reads published skills" on public.skills for select using (published); create policy "public reads published experience" on public.experience for select using (published); create policy "public reads published certificates" on public.certificates for select using (published); create policy "public reads published education" on public.education for select using (published); create policy "public reads published testimonials" on public.testimonials for select using (published); create policy "public reads published blog" on public.blog for select using (published); create policy "public profile" on public.profile for select using(true); create policy "public settings" on public.site_settings for select using(true); create policy "public sends messages" on public.messages for insert with check(true);
-- A single authenticated portfolio owner is assumed per student project. Authenticated users manage content.
do $$ declare t text; begin foreach t in array array['profile','site_settings','projects','skills','experience','certificates','education','testimonials','blog','messages'] loop execute format('create policy "admin manages %s" on public.%I for all to authenticated using (true) with check (true)',t,t); end loop; end $$;
insert into storage.buckets(id,name,public) values ('portfolio-assets','portfolio-assets',true) on conflict do nothing; create policy "public assets" on storage.objects for select using(bucket_id='portfolio-assets'); create policy "admin assets" on storage.objects for all to authenticated using(bucket_id='portfolio-assets') with check(bucket_id='portfolio-assets');
alter publication supabase_realtime add table public.projects,public.skills,public.experience,public.certificates,public.education,public.testimonials,public.blog,public.profile;
create or replace function public.clear_portfolio_data() returns void language plpgsql security definer as $$ begin delete from projects;delete from skills;delete from experience;delete from certificates;delete from education;delete from testimonials;delete from blog;delete from messages;delete from profile; end $$;
create or replace function public.seed_demo_data() returns void language plpgsql security definer as $$ begin insert into projects(title,summary,tools,domain,published,featured,impact) values ('{"en":"Retail margin command center"}','{"en":"Power BI profitability cockpit for 120 stores."}',array['Power BI','SQL'],'Retail',true,true,28); end $$;
grant execute on function public.clear_portfolio_data() to authenticated; grant execute on function public.seed_demo_data() to authenticated;
